INSERT INTO questions (text) VALUES
('What is your favorite book and why?'),
('How many languages do you speak fluently?'),
('What is the most beautiful place you have ever visited?'),
('Can you name a person who has had a major impact on your life?'),
('Have you ever experienced a natural disaster?'),
('What is your favorite type of cuisine and why?'),
('Do you prefer indoor or outdoor activities?'),
('What is your favorite song and why?'),
('What is your favorite animal and why?'),
('Have you ever been to a concert or festival?'),
('What is your favorite sport and why?'),
('What is the most interesting thing you have ever learned?'),
('What is your favorite movie and why?'),
('Do you have any pets? If so, what kind?'),
('What is the best vacation you have ever taken?'),
('Have you ever been skydiving or bungee jumping?'),
('What is your favorite hobby and why?'),
('What is your favorite season and why?'),
('What is your favorite type of art and why?'),
('What is your favorite type of flower and why?'),
('Do you prefer the beach or the mountains?'),
('What is your favorite type of music and why?'),
('Have you ever been scuba diving or snorkeling?'),
('What is the most adventurous thing you have ever done?'),
('What is your favorite type of car and why?'),
('What is your favorite type of tree and why?'),
('Do you prefer sweet or savory foods?'),
('What is your favorite thing to do on a lazy day?'),
('What is your favorite childhood memory?'),
('What is your favorite type of shoe and why?'),
('Have you ever gone camping or hiking?'),
('What is the most important thing in your life?'),
('What is your favorite type of drink and why?'),
('What is the most beautiful sunset you have ever seen?'),
('Do you prefer hot or cold weather?'),
('What is your favorite type of candy and why?'),
('What is your favorite thing to do with friends?'),
('What is your favorite type of pasta and why?'),
('What is your favorite time of day and why?'),
('What is your favorite type of pizza and why?'),
('What is your favorite type of breakfast food and why?'),
('Do you prefer coffee or tea?'),
('What is the most interesting place you have ever been to?'),
('What is your favorite thing to do with family?'),
('What is your favorite type of vegetable and why?'),
('What is your favorite type of sandwich and why?'),
('Do you prefer fiction or non-fiction books?'),
('What is your favorite type of cookie and why?'),
('What is the most amazing sight you have ever seen?'),
('What is your favorite thing to do when you are feeling stressed?'),
('What is your favorite type of fish and why?'),
('What is the most delicious meal you have ever had?'),
('Do you prefer to travel by car or by plane?'),
('What is your favorite type of wine and why?'),
('What is the most memorable event you have ever attended?'),
('What is your favorite type of cheese and why?'),
('Do you prefer to stay in or go out on the weekend?'),
('What is your favorite type of fruit and why?'),
('What is the most challenging thing you have ever done?'),
('What is your favorite type of soup and why?'),
('What is your favorite type of bird and why?'),
('What is your favorite type of museum and why?'),
('What is your favorite type of beer and why?'),
('What is your favorite type of dessert and why?'),
('What is the most exciting thing you have ever done?'),
('What is your favorite type of plant and why?'),
('Do you prefer to cook at home or eat out?'),
('What is your favorite type of bread and why?'),
('What is the most unique gift you have ever received?'),
('What is your favorite type of jewelry and why?'),
('What is your favorite type of fruit juice and why?'),
('What is your favorite type of shoe brand and why?'),
('Do you prefer to watch movies or TV shows?'),
('What is your favorite type of car brand and why?'),
('What is the most valuable thing you own?'),
('What is your favorite type of architecture and why?'),
('What is your favorite type of coffee and why?'),
('What is the most inspiring book you have ever read?'),
('What is your favorite type of weather and why?'),
('What is your favorite type of tree fruit and why?'),
('What is your favorite type of ocean animal and why?'),
('What is the most delicious snack you have ever had?'),
('What is your favorite type of museum exhibit and why?'),
('What is your favorite type of flower arrangement and why?'),
('What is the most challenging goal you have ever achieved?'),
('What is your favorite type of sport team and why?'),
('What is your favorite type of ice cream and why?'),
('What is your favorite type of house plant and why?'),
('What is your favorite type of board game and why?'),
('What is the most meaningful gift you have ever given?'),
('What is your favorite type of music genre and why?'),
('What is your favorite type of book genre and why?'),
('What is the most interesting animal you have ever seen?'),
('What is your favorite type of bird species and why?'),
('What is your favorite type of kitchen gadget and why?'),
('What is the most memorable trip you have ever taken?'),
('What is your favorite type of sofa and why?'),
('What is your favorite type of ice cream topping and why?'),
('What is the most unique place you have ever stayed?'),
('What is your favorite type of cocktail and why?'),
('What is your favorite type of sport to watch and why?'),
('What is your favorite type of fabric and why?'),
('What is the most inspiring person you have ever met?'),
('What is your favorite type of souvenir to bring back from a trip and why?'),
('What is your favorite type of martial arts and why?'),
('What is the most interesting piece of art you have ever seen?'),
('What is your favorite type of kitchen appliance and why?'),
('What is your favorite type of travel destination and why?'),
('What is the most unique food you have ever tried?'),
('What is your favorite type of snack and why?'),
('What is your favorite type of boat and why?'),
('What is the most interesting historical fact you know?'),
('What is your favorite type of hair accessory and why?'),
('What is your favorite type of outdoor activity and why?'),
('What is the most unique souvenir you have ever brought back from a trip?'),
('What is your favorite type of romantic gesture and why?'),
('What is your favorite type of kitchen tool and why?'),
('What is the most beautiful piece of clothing you have ever owned?'),
('What is your favorite type of cheese dish and why?'),
('What is your favorite type of bird song and why?');
